[tool.poetry]
name = "logia"
version = "0.1.0"
description = ""
authors = ["mzsm <mizushimaj@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12.1,<3.13"
faster-whisper = "^1.0.1"
mlx = "^0.10.0"
numba = "^0.59.1"
numpy = "^1.26.4"
torch = "^2.2.1"
tqdm = "^4.66.2"
more-itertools = "^10.2.0"
tiktoken = "^0.6.0"
huggingface-hub = "^0.22.2"
scipy = "^1.12.0"
ujson = "^5.9.0"
pyinstaller = "^6.6.0"
ctranslate2 = "4.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
